---
- hosts: all
  connection: local
      
  tasks:
   - name: Crear directorio {{hostvars.localhost.DT}}
     file:
      path: /var/lib/awx/projects/Playbooks/ARP_SW72
      state: directory
     run_once: true
     delegate_to: localhost

   - name: Informacion ARP y MAC
     ios_command:
       commands:
           - sh ip arp | i Vlan81
           - sh mac address-table vlan 81 | e CPU
     register: a

   - name: debug en pantalla
     debug:
       msg:
          - "{{ a }}"
          - "{{ a.stdout_lines }}"

   - name: accion
     copy:
       content: "{{ a.stdout_lines }}"
       dest: "/var/lib/awx/projects/Playbooks/ARP_SW72/{{ inventory_hostname }}.txt"
     delegate_to: localhost
