---
- hosts: all
  connection: local
  vars:
    cli:
       username: ansiblepr
       password: Generica2020
       auth_pass: m1ll3c4ll
       authorize: yes
       timeout: 30
       
  tasks:
   - name: Crear directorio {{hostvars.localhost.DT}}
     file:
      path: /etc/ansible/ARP_SWBQ
      state: directory
     run_once: true

  - name: Informacion DHCP BINDING
    ios_command:
      provider : "{{ cli }}"
      commands:
          - sh ip dhcp binding
            #          - sh mac address-table vlan 81 | e CPU
          - sh clock
    register: a

  - name: debug en pantalla
    debug:
      msg:
         - "{{ a.stdout_lines }}"

  - name: accion
    copy:
      content: "{{ a.stdout_lines }}"
      dest: "/etc/ansible/ARP_SWBQ/{{ inventory_hostname }}.txt"
    delegate_to: localhost
