---
- hosts: all
  connection: local

  tasks:

  - name: show version
    ios_command:
      commands:
          - sh run
      timeout: 30
    register: a

  - name: debug en pantalla
    debug:
      msg:
         - "{{ a.stdout_lines }}"
