---
- hosts: localhost

  tasks:

   - name: Mail sending using Mail Module
     mail:
       host: "smtp.office365.com"
       port: 587
       username: "{{ correo }}"
       password: "{{ clave }}"
       from: "{{ correo }}"
       to:
        - "{{ correo_ETB }}"
       cc:
        -  "{{ correo_NET }}"
       subject: Millenum BPO | Limpieza tabla ARP-CRCs | CAV30CI1065030 / CAV30CI1065028
       body: |
        Buen día, Ingenieros ETB
        
        Agradecemos la creación de un caso de soporte para realizar una limpieza de tabla ARP y de CRC en las interfaces, para el canal relacionado a los IDs CAV30CI1065030 / CAV30CI1065028
        
        Cordialmente,
        Juan Esteban Ladino Antolinez
        Ingeniero de Networking
       secure: starttls 
