---
- hosts: all
  connection: local

  tasks:

  - name: show version
    ios_command:
      commands:
          - sh ver | i uptime
          - sh inventory
          - sh run | i hostname s
    register: a

  - name: debug en pantalla
    debug:
      msg:
         - "{{ a.stdout_lines }}"


  - name: Extraccion de interfaz
    ios_command:
      commands: sh ip int br | i Vlan24
    register: a1

  - name: debug de la vlan
    debug:
      msg: "{{ a1.stdout_lines }}"


  - set_fact:
      c: "{{ (a1.stdout_lines[0] | regex_replace(' ', '*')).split('*')[0]}}"

  - name:
    debug:
      msg: "{{ c[2:] }}"


  - name: prueba de ping
    ios_ping:
      source: "{{ c[2:] }}"
      dest: 8.8.8.8
    register: a3

  - name: debug del ping
    debug:
            msg:
             -  "El tiempo promedio a internet por el canal de ETB es: {{ a3.rtt.avg }} ms"
             -  "El tiempo Maximo a internet por el canal de ETB es: {{ a3.rtt.max }} ms"
             -  "El tiempo min a internet por el canal de ETB es: {{ a3.rtt.min }} ms"
             -  "Cantidad de paquetes perdidos: {{ a3.packet_loss }}"

